# Generated by Django 5.0.2 on 2025-06-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_manager', '0003_borrowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='fine_amount',
        ),
    ]
